import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className="border-b p-6">
            <p className="text-4xl font-bold">DT NFT Marketplace</p>
            <div className="flex mt-4">
              <Link href="/" className="mr-4 text-blue-500">
                Market
              </Link>
              <Link href="/create-item" className="mr-6 text-blue-500">
                Sell NFTs
              </Link>
              <Link href="/my-assets" className="mr-6 text-blue-500">
                My NFTs
              </Link>
              <Link href="/creator-dashboard" className="mr-6 text-blue-500">
                Dashboard
              </Link>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
